### ISSUE TITLE
missing image feature files?

### ISSUE THREAD

**Issue by jmhessel** [hwanheelee1993/ViLBERTScore#1]
Hi there!

Thanks for the code release! Just wanted to give a quick heads up --- it looks like the image feature files might be missing from flickr8k here:

https://drive.google.com/drive/folders/1W6cK3KJnxwPcbLriL8LTSwjA5qKbnkoR

Thanks!
Jack

**Comment by hwanheelee1993** [comment]
Hi Jack.

Sorry for the missing file.

It seems that the file was not uploaded because it exceeded the limit of my
Google Drive account due to its large capacity. I checked and found that
the size is about 8GB. I will upload it again until tomorrow in a different
link.

Thanks for the waiting.
Henry


2021년 4월 6일 (화) 오전 9:17, Jack Hessel ***@***.***>님이 작성:

**Comment by jmhessel** [comment]
Thank you!! :-)

**Comment by jmhessel** [comment]
Hey @hwanheelee1993  --- just curious if you had a chance to upload those image files yet, I'd love to play around with them! :-)

**Comment by hwanheelee1993** [comment]
> Hey @hwanheelee1993 --- just curious if you had a chance to upload those image files yet, I'd love to play around with them! :-)

Sorry for the late update. I changed the whole link from googledrive to our file server!.

Thanks for the waiting.

**Comment by jmhessel** [comment]
Thanks so much!!
